--- 
- hosts: localhost
  become: yes
  gather_facts: no
  
  tasks:
    # Play to install apache2 and mysql using a loop with with_items
    - name: Install apache2 and mysql
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apache2
        - mysql-server
        - mysql-client

 # Play to install pip normally    
    -name: Install pip
      apt:
        name: python-pip
        state: present

# play to check if services are running using vars
    - name: Confirm services are running
      services:
        name: "{{ item }}"
        state: started
      with_items:
        - apache2
        - mysql